import "~/styles/globals.css";

import { AppSidebar } from "./_components/app-sidebar";
import { Inter } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SiteHeader } from "./_components/site-header";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "./_components/ui/toaster";
import TopNavbar from "./_components/TopNavbar";
import { cookies } from "next/headers";
import { getServerAuthSession } from "~/server/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  const cookieStore = cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  return (
    <html lang="en" className={`${inter.variable}`} suppressHydrationWarning>
      <body>
        <TRPCReactProvider>
          <div className="flex min-h-screen">
            {/* <SidebarProvider defaultOpen={defaultOpen}> */}
            {/* <AppSidebar /> */}
            <main className="flex-1">
              <SiteHeader />
              {children}
            </main>
            {/* </SidebarProvider> */}
          </div>
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
